# Generated by Django 4.1.3 on 2022-11-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fio',
            new_name='group',
        ),
    ]
